/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domeni.Mesto;
import domeni.Zaposleni;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import operacije.Operacije;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Darko
 */
public class KlijentForma extends javax.swing.JFrame {

    Zaposleni z = new Zaposleni();

    /**
     * Creates new form KlijentForma
     */
    public KlijentForma(Zaposleni novi) {
        initComponents();
        this.z = novi;
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                odjaviZaposlenog();
                dispose();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Operacije");

        jMenuItem1.setText("Sacuvaj pravno lice");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem5.setText("Sacuvaj zaposlenog");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem2.setText("Prikaz i pretraga zaposlenih");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem4.setText("Prikaz i pretraga pravnih lica");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem6.setText("Sacuvaj i prikazi mesto/grad");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem3.setText("Odjava");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        KlijentskiZahtev kz = new KlijentskiZahtev(Operacije.vratiMesta, null);
        Komunikacija.getInstance().posaljiZahtev(kz);

//
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();
        List<Mesto> mesta = (List<Mesto>) so.getOdgovor();
        if (mesta != null) {

            SacuvajPravnoLiceForma forma = new SacuvajPravnoLiceForma(mesta, z);
            forma.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "ne mogu da povucem mesta iz baze");
        }


    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        KlijentskiZahtev kz = new KlijentskiZahtev(Operacije.vratiZaposlene, null);
        Komunikacija.getInstance().posaljiZahtev(kz);

//
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();
        List<Zaposleni> zaposleni = (List<Zaposleni>) so.getOdgovor();

        PrikazZaposleniForma pzf = new PrikazZaposleniForma(zaposleni);
        pzf.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        KlijentskiZahtev kz = new KlijentskiZahtev(Operacije.odjava, z);
        Komunikacija.getInstance().posaljiZahtev(kz);

//
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();
        boolean odjavljen = (boolean) so.getOdgovor();

        if (odjavljen == true) {
            JOptionPane.showMessageDialog(this, "uspesno odjavljen");
        } else {
            JOptionPane.showMessageDialog(this, "greska");
        }
        this.dispose();

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed

        KlijentskiZahtev kz = new KlijentskiZahtev(Operacije.vratiMesta, null);
        Komunikacija.getInstance().posaljiZahtev(kz);

        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();
        List<Mesto> mesta = (List<Mesto>) so.getOdgovor();

        if (mesta != null) {
            PrikazPravnihLicaForma pz = new PrikazPravnihLicaForma();
            pz.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Ne mogu da povučem mesta iz baze.");
        }

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        SacuvajZaposlenogForma szf = new SacuvajZaposlenogForma();
        szf.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        SacuvajMestoForma smf = new SacuvajMestoForma();
        smf.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    private void odjaviZaposlenog() {
        try {
            KlijentskiZahtev kz = new KlijentskiZahtev(Operacije.odjava, z);
            Komunikacija.getInstance().posaljiZahtev(kz);

            ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();
            boolean odjavljen = (boolean) so.getOdgovor();

            if (!odjavljen) {
                JOptionPane.showMessageDialog(this, "Greška pri odjavi.");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Greška pri odjavi: " + ex.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    // End of variables declaration//GEN-END:variables
}
