/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domeni.Zaposleni;
import java.util.ArrayList;
import java.util.List;
import modeli.ModelTabeleZaposleni;
import komunikacija.Komunikacija;
import operacije.Operacije;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;
import javax.swing.JOptionPane;

/**
 *
 * @author Darko
 */
public class PrikazZaposleniForma extends javax.swing.JFrame {

    List<Zaposleni> zaposleni = new ArrayList<>();
    ModelTabeleZaposleni mtz;

    /**
     * Creates new form PrikazZaposleniForma
     */
    public PrikazZaposleniForma(List<Zaposleni> zaposleni) {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setSize((int) (screenSize.width * 0.6), (int) (screenSize.height * 0.6));

        setLocationRelativeTo(null);
        this.zaposleni = zaposleni;
        mtz = new ModelTabeleZaposleni(zaposleni);
        jTable1.setModel(mtz);
        osveziTabelu();
    }
    
    public PrikazZaposleniForma() {
    initComponents();
    setDefaultCloseOperation(DISPOSE_ON_CLOSE);

    java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
    setSize((int) (screenSize.width * 0.6), (int) (screenSize.height * 0.6));

    setLocationRelativeTo(null);

    zaposleni = new ArrayList<>();
    mtz = new ModelTabeleZaposleni(zaposleni);
    jTable1.setModel(mtz);

    // 🔥 OVO JE KLJUČNO
    osveziTabeluIzBaze();
}

    public void osveziTabelu() {
        mtz.fireTableDataChanged();
    }

    public void osveziTabeluIzBaze() {
        KlijentskiZahtev kz = new KlijentskiZahtev(Operacije.vratiZaposlene, null);
        Komunikacija.getInstance().posaljiZahtev(kz);
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();

        List<Zaposleni> novaLista = (List<Zaposleni>) so.getOdgovor();

        this.zaposleni = novaLista;
        mtz.setLista(novaLista);
        mtz.fireTableDataChanged();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonDetaljnije = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Pretraga");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Unesite ime i prezime za pretragu:");

        jButtonDetaljnije.setText("Detaljnije");
        jButtonDetaljnije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetaljnijeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(jButtonDetaljnije, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(252, 252, 252))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 222, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jButtonDetaljnije)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String imeIprezime = jTextField1.getText().trim().toLowerCase();

        List<Zaposleni> filtrirani = new ArrayList<>();

        for (Zaposleni zaposleni1 : zaposleni) {
            String celoIme = (zaposleni1.getIme() + " " + zaposleni1.getPrezime()).toLowerCase();
            if (celoIme.contains(imeIprezime)) {
                filtrirani.add(zaposleni1);
            }

        }
        ModelTabeleZaposleni mt = (ModelTabeleZaposleni) jTable1.getModel();
        mt.setLista(filtrirani);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonDetaljnijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetaljnijeActionPerformed
        int red = jTable1.getSelectedRow();

        if (red == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Izaberite zaposlenog iz tabele.");
            return;
        }

        ModelTabeleZaposleni mt = (ModelTabeleZaposleni) jTable1.getModel();
        Zaposleni z = mt.vratiZaposlenog(red);

        SacuvajZaposlenogForma forma = new SacuvajZaposlenogForma(z, this);
        forma.setVisible(true);
    }//GEN-LAST:event_jButtonDetaljnijeActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonDetaljnije;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
