/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domeni.Zaposleni;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import operacije.Operacije;
import transfer.KlijentskiZahtev;
import transfer.ServerskiOdgovor;

/**
 *
 * @author Darko
 */
public class SacuvajZaposlenogForma extends javax.swing.JFrame {
private Zaposleni zaposleni;
private PrikazZaposleniForma roditelj;
    /**
     * Creates new form SacuvajZaposlenogForma
     */



   public SacuvajZaposlenogForma() {
    initComponents();
    setLocationRelativeTo(null);
    setDefaultCloseOperation(DISPOSE_ON_CLOSE);

    jButton1.setText("Sacuvaj zaposlenog");
    jButtonObrisi.setVisible(false);
}
   public SacuvajZaposlenogForma(Zaposleni zaposleni) {
    initComponents();
    setLocationRelativeTo(null);
    setDefaultCloseOperation(DISPOSE_ON_CLOSE);

    this.zaposleni = zaposleni;

    jTextFieldIme.setText(zaposleni.getIme());
    jTextFieldPrezime.setText(zaposleni.getPrezime());
    jTextFieldKorisnickoIme.setText(zaposleni.getKorisnickoIme());
    jPasswordField1.setText(zaposleni.getLozinka());

    jButton1.setText("Sacuvaj izmene");
    jButtonObrisi.setVisible(true);
}
   public SacuvajZaposlenogForma(Zaposleni zaposleni, PrikazZaposleniForma roditelj) {
    initComponents();
    setLocationRelativeTo(null);
    setDefaultCloseOperation(DISPOSE_ON_CLOSE);

    this.zaposleni = zaposleni;
    this.roditelj = roditelj;

    jTextFieldIme.setText(zaposleni.getIme());
    jTextFieldPrezime.setText(zaposleni.getPrezime());
    jTextFieldKorisnickoIme.setText(zaposleni.getKorisnickoIme());
    jPasswordField1.setText(zaposleni.getLozinka());

    jButton1.setText("Sacuvaj izmene");
    jButtonObrisi.setVisible(true);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldIme = new javax.swing.JTextField();
        jTextFieldPrezime = new javax.swing.JTextField();
        jTextFieldKorisnickoIme = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButtonObrisi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ime:");

        jLabel2.setText("Prezime:");

        jLabel3.setText("Korisnicko ime:");

        jLabel4.setText("Lozinka:");

        jButton1.setText("Sacuvaj zaposlenog");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonObrisi.setText("Obrisi");
        jButtonObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(118, 118, 118)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                    .addComponent(jTextFieldIme)
                    .addComponent(jTextFieldPrezime)
                    .addComponent(jTextFieldKorisnickoIme)
                    .addComponent(jPasswordField1))
                .addContainerGap(130, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldKorisnickoIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonObrisi)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   String ime = jTextFieldIme.getText().trim();
    String prezime = jTextFieldPrezime.getText().trim();
    String korisnickoIme = jTextFieldKorisnickoIme.getText().trim();
    String lozinka = new String(jPasswordField1.getPassword()).trim();

    if (ime.isEmpty() || prezime.isEmpty() || korisnickoIme.isEmpty() || lozinka.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Sva polja su obavezna.");
        return;
    }

    if (zaposleni == null) {
        Zaposleni z = new Zaposleni();
        z.setIme(ime);
        z.setPrezime(prezime);
        z.setKorisnickoIme(korisnickoIme);
        z.setLozinka(lozinka);

        KlijentskiZahtev kz = new KlijentskiZahtev(Operacije.sacuvajZaposlenog, z);

        Komunikacija.getInstance().posaljiZahtev(kz);
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();

        boolean uspesno = (boolean) so.getOdgovor();

        if (uspesno) {
            int odgovor = JOptionPane.showConfirmDialog(
                    this,
                    "Uspešno sačuvan zaposleni.\nDa li želite da sačuvate još zaposlenih?",
                    "Potvrda",
                    JOptionPane.YES_NO_OPTION
            );

            if (odgovor == JOptionPane.YES_OPTION) {
                jTextFieldIme.setText("");
                jTextFieldPrezime.setText("");
                jTextFieldKorisnickoIme.setText("");
                jPasswordField1.setText("");
                jTextFieldIme.requestFocus();
            } else {
                dispose();
            }

        } else {
            JOptionPane.showMessageDialog(this, "Sistem ne može da sačuva zaposlenog.");
        }

    } else {
        zaposleni.setIme(ime);
        zaposleni.setPrezime(prezime);
        zaposleni.setKorisnickoIme(korisnickoIme);
        zaposleni.setLozinka(lozinka);

        KlijentskiZahtev kz = new KlijentskiZahtev(Operacije.izmeniZaposlenog, zaposleni);

        Komunikacija.getInstance().posaljiZahtev(kz);
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();

        boolean uspesno = (boolean) so.getOdgovor();

        if (uspesno) {
    JOptionPane.showMessageDialog(this, "Uspešno izmenjen zaposleni.");

    if (roditelj != null) {
        roditelj.osveziTabeluIzBaze();
    }

    dispose();
} else {
            JOptionPane.showMessageDialog(this, "Sistem ne može da izmeni zaposlenog.");
        }
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiActionPerformed
 if (zaposleni == null) {
        return;
    }

    int odgovor = JOptionPane.showConfirmDialog(
            this,
            "Da li ste sigurni da želite da obrišete zaposlenog?",
            "Potvrda brisanja",
            JOptionPane.YES_NO_OPTION
    );

    if (odgovor == JOptionPane.YES_OPTION) {
        KlijentskiZahtev kz = new KlijentskiZahtev(Operacije.obrisiZaposlenog, zaposleni);

        Komunikacija.getInstance().posaljiZahtev(kz);
        ServerskiOdgovor so = Komunikacija.getInstance().primiOdgovor();

        boolean uspesno = (boolean) so.getOdgovor();

        if (uspesno) {
    JOptionPane.showMessageDialog(this, "Uspešno obrisan zaposleni.");

    if (roditelj != null) {
        roditelj.osveziTabeluIzBaze();
    }

    dispose();
} else {
            JOptionPane.showMessageDialog(this, "Sistem ne može da obriše zaposlenog.");
        }
    }

    }//GEN-LAST:event_jButtonObrisiActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonObrisi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextFieldIme;
    private javax.swing.JTextField jTextFieldKorisnickoIme;
    private javax.swing.JTextField jTextFieldPrezime;
    // End of variables declaration//GEN-END:variables
}
